(* ::Package:: *)

(* ::Input:: *)
(*ClearAll["Global`*"]*)
(*SetDirectory["/Users/humayrajeba/Documents/Wolfram Mathematica/processed_data_dBm"];*)
(*data=Import["updated_racing_7.txt","Table"];*)
(*micromobility=data[[All,2]];*)
(*SetDirectory["/Users/humayrajeba/Documents/Wolfram Mathematica/THzBlock"];*)
(*data=Import["Set3_H=135cm_L13=450cm_L12=300cm/DATA_UNCAL_Meas22","Table"];*)
(*avgParam=20;*)
(*percentage=5;*)
(*blockage=data[[All,2]];*)


(* ::Input:: *)
(*micromobility*)
(*blockage*)


(* ::Input:: *)
(*(*Calculate the weighted signal and its exponential moving average*)*)
(*block1=10*Log10[blockage]*)


(* ::Input:: *)
(*micro1=Take[micromobility]*)


(* ::Input:: *)
(*microPeriodogram=PeriodogramArray@micro1*)
(*ListLinePlot[micro1,PlotRange->All]*)
(**)
(*blockPeriodogram=PeriodogramArray@block1*)
(*ListLinePlot[block1+35,PlotRange->All]*)
(**)


(* ::Input:: *)
(*microPeriodogram=PeriodogramArray[micro1];*)
(*blockPeriodogram=PeriodogramArray[block1];*)
(**)
(*ListLinePlot[{micro1,block1+35},PlotRange->All,PlotLegends->Placed[{"Micro1","Block1"},{0.8,0.8}]]*)
(**)


(* ::Input:: *)
(*ListLinePlot[{micro1[[30000;;80000]],block1[[20000;;70000]]+9},PlotRange->All,PlotStyle->{BlueGray},PlotLegends->Placed[{"Micro1","Block1"},{0.8,0.8}]]*)
(**)


(* ::Input:: *)
(*block=block1+35*)
(*decayRate1=0.001;*)
(*movingAvg1=Re[ExponentialMovingAverage[block,decayRate1]]*)
(*ListLinePlot[movingAvg1,PlotRange->All]*)
(*decayRate2=0.0001;*)
(*movingAvg2=Re[ExponentialMovingAverage[block,decayRate2]]*)
(*ListLinePlot[movingAvg2,PlotRange->All]*)


(* ::Input:: *)
(*movingAvg3=Re[ExponentialMovingAverage[micromobility,decayRate1]]*)
(*ListLinePlot[movingAvg3,PlotRange->All]*)
(*movingAvg4=Re[ExponentialMovingAverage[micromobility,decayRate2]]*)
(*ListLinePlot[movingAvg4,PlotRange->All]*)


(* ::Input:: *)
(*ListLinePlot[{movingAvg1[[20000;;70000]],movingAvg3[[20000;;70000]]},PlotRange->{{20000,50000},All},PlotStyle->{BlueGray},PlotLegends->Placed[{"Micro for 0.001","Block for 0.001"},{0.8,0.7}]]*)


(* ::Input:: *)
(*ListLinePlot[{movingAvg2[[20000;;70000]],movingAvg4[[20000;;70000]]+16},PlotRange->{{20000,50000},All},PlotStyle->{BlueGray},PlotLegends->Placed[{"Micro for 0.0001","Block for 0.0001"},{0.8,0.7}]]*)


(* ::Input:: *)
(*(*Initialize the list to store the sum of periodograms without decay rate*)*)
(*sumPeriodograms={};*)
(**)
(*(*Calculate the number of segments*)*)
(*numSegments=Quotient[Length[block],500];*)
(**)
(*(*Loop through each segment*)*)
(*For[i=1,i<=numSegments,i++,*)
(*(*Extract the i^th segment of 500 values*)*)
(*blockSegment=Take[block,{500*(i-1)+1,500*i}];*)
(*(*Compute the periodogram for the current segment*)*)
(*periodogram=PeriodogramArray[blockSegment];*)
(*(*Sum up the values of the periodogram*)*)
(*sumPeriodogram=Total[periodogram];*)
(*(*Append the sum to the list*)*)
(*AppendTo[sumPeriodograms,sumPeriodogram];]*)
(**)
(*(*Output the list of summed periodograms for blockage trace*)*)
(*sumPeriodograms*)


(* ::Input:: *)
(*(*Plot the summed periodograms for blockage trace*)*)
(*ListLinePlot[sumPeriodograms,PlotRange->All,*)
(*PlotLabel->"Summed Periodograms for blockage original",*)
(*AxesLabel->{"Segment Index","Sum of Periodogram Values"}]*)
(*(*Plot the summed periodograms with smaller dots and thinner lines*)ListPlot[sumPeriodograms,Joined->True,PlotStyle->{Blue,Thin},PlotRange->All,PlotMarkers->{Automatic,Small},PlotLabel->"Summed Periodograms for blockage",AxesLabel->{"Segment Index","Sum of Periodogram Values"},ImageSize->Large]*)


(* ::Input:: *)
(*(*Initialize the list to store the sum of periodograms without decay rate*)*)
(*sumPeriodograms1={};*)
(**)
(*(*Calculate the number of segments*)*)
(*numSegments1=Quotient[Length[micromobility],500];*)
(**)
(*(*Loop through each segment*)*)
(*For[i=1,i<=numSegments1,i++,*)
(*(*Extract the i^th segment of 500 values*)*)
(*microSegment1=Take[micromobility,{500*(i-1)+1,500*i}];*)
(*(*Compute the periodogram for the current segment*)*)
(*periodogram1=PeriodogramArray[microSegment1];*)
(*(*Sum up the values of the periodogram*)*)
(*sumPeriodogram1=Total[periodogram1];*)
(*(*Append the sum to the list*)*)
(*AppendTo[sumPeriodograms1,sumPeriodogram1];]*)
(**)
(*(*Output the list of summed periodograms for micromobility*)*)
(*sumPeriodograms1*)


(* ::Input:: *)
(*(*Plot the summed periodograms*)*)
(*ListLinePlot[sumPeriodograms1,PlotRange->All,*)
(*PlotLabel->"Summed Periodograms for micromobility original",*)
(*AxesLabel->{"Segment Index","Sum of Periodogram Values"}]*)
(*(*Plot the summed periodograms with smaller dots and thinner lines*)ListPlot[sumPeriodograms1,Joined->True,PlotStyle->{Blue,Thin},PlotRange->All,PlotMarkers->{Automatic,Small},PlotLabel->"Summed Periodograms for micromobility",AxesLabel->{"Segment Index","Sum of Periodogram Values"},ImageSize->Large]*)


(* ::Input:: *)
(*ListLinePlot[{sumPeriodograms1+46152,sumPeriodograms},PlotRange->{{0,163},All},PlotStyle->{BlueGray},PlotLabel->"Summed Periodograms original micromobility & blockage",PlotLegends->Placed[{"Micro original","Block original"},{0.8,0.8}]]*)


(* ::Input:: *)
(*(*Initialize the list to store the sum of periodograms with 0.001 decay rate for blockage*)*)
(*sumPeriodograms2={};*)
(**)
(*(*Calculate the number of segments*)*)
(*numSegments2=Quotient[Length[movingAvg1],500];*)
(**)
(*(*Loop through each segment*)*)
(*For[i=1,i<=numSegments2,i++,*)
(*(*Extract the i^th segment of 500 values*)*)
(*blockSegment2=Take[movingAvg1,{500*(i-1)+1,500*i}];*)
(*(*Compute the periodogram for the current segment*)*)
(*periodogram2=PeriodogramArray[blockSegment2];*)
(*(*Sum up the values of the periodogram*)*)
(*sumPeriodogram2=Total[periodogram2];*)
(*(*Append the sum to the list*)*)
(*AppendTo[sumPeriodograms2,sumPeriodogram2];]*)
(**)
(*(*Output the list of summed periodograms for blockage trace*)*)
(*sumPeriodograms2*)
(*(*Plot the summed periodograms for 0.001*)*)
(*ListLinePlot[sumPeriodograms2,PlotRange->All,*)
(*PlotLabel->"Summed Periodograms for 0.001 of blockage",*)
(*AxesLabel->{"Segment Index","Sum of Periodogram Values"}]*)
(*(*Plot the summed periodograms with smaller dots and thinner lines*)ListPlot[sumPeriodograms2,Joined->True,PlotStyle->{Blue,Thin},PlotRange->All,PlotMarkers->{Automatic,Small},PlotLabel->"Summed Periodograms for 0.001 of blockage",AxesLabel->{"Segment Index","Sum of Periodogram "},ImageSize->Large]*)
(**)


(* ::Input:: *)
(*(*Initialize the list to store the sum of periodograms with 0.001 decay rate for micromobility*)*)
(*sumPeriodograms3={};*)
(**)
(*(*Calculate the number of segments*)*)
(*numSegments3=Quotient[Length[movingAvg3],500];*)
(**)
(*(*Loop through each segment*)*)
(*For[i=1,i<=numSegments2,i++,*)
(*(*Extract the i^th segment of 500 values*)*)
(*blockSegment3=Take[movingAvg3,{500*(i-1)+1,500*i}];*)
(*(*Compute the periodogram for the current segment*)*)
(*periodogram3=PeriodogramArray[blockSegment3];*)
(*(*Sum up the values of the periodogram*)*)
(*sumPeriodogram3=Total[periodogram3];*)
(*(*Append the sum to the list*)*)
(*AppendTo[sumPeriodograms3,sumPeriodogram3];]*)
(**)
(*(*Output the list of summed periodograms for micromobility trace*)*)
(*sumPeriodograms3*)
(*(*Plot the summed periodograms for 0.001*)*)
(*ListLinePlot[sumPeriodograms3,PlotRange->All,*)
(*PlotLabel->"Summed Periodograms for 0.001 micromobility",*)
(*AxesLabel->{"Segment Index","Sum of Periodogram "}]*)
(*(*Plot the summed periodograms with smaller dots and thinner lines*)ListPlot[sumPeriodograms3,Joined->True,PlotStyle->{Blue,Thin},PlotRange->All,PlotMarkers->{Automatic,Small},PlotLabel->"Summed Periodograms for 0.001 micromobility",AxesLabel->{"Segment Index","Sum of Periodogram "},ImageSize->Large]*)
(**)


(* ::Input:: *)
(*ListLinePlot[{sumPeriodograms3+101495,sumPeriodograms2},PlotRange->All,PlotStyle->{BlueGray},PlotLabel->"Summed Periodograms for 0.001 micromobility & blockage",PlotLegends->Placed[{"Micro in 0.001","Block in 0.001"},{0.8,0.8}]]*)


(* ::Input:: *)
(*(*Initialize the list to store the sum of periodograms with 0.0001 decay rate for blockage*)*)
(*sumPeriodograms4={};*)
(**)
(*(*Calculate the number of segments*)*)
(*numSegments4=Quotient[Length[movingAvg2],500];*)
(**)
(*(*Loop through each segment*)*)
(*For[i=1,i<=numSegments4,i++,*)
(*(*Extract the i^th segment of 500 values*)*)
(*blockSegment4=Take[movingAvg2,{500*(i-1)+1,500*i}];*)
(*(*Compute the periodogram for the current segment*)*)
(*periodogram4=PeriodogramArray[blockSegment4];*)
(*(*Sum up the values of the periodogram*)*)
(*sumPeriodogram4=Total[periodogram4];*)
(*(*Append the sum to the list*)*)
(*AppendTo[sumPeriodograms4,sumPeriodogram4];]*)
(**)
(*(*Output the list of summed periodograms for blockage trace*)*)
(*sumPeriodograms4*)
(*(*Plot the summed periodograms for 0.0001*)*)
(*ListLinePlot[sumPeriodograms4,PlotRange->All,*)
(*PlotLabel->"Summed Periodograms for 0.0001 blockage",*)
(*AxesLabel->{"Segment Index","Sum of Periodogram "}]*)
(*(*Plot the summed periodograms with smaller dots and thinner lines*)ListPlot[sumPeriodograms4,Joined->True,PlotStyle->{Blue,Thin},PlotRange->All,PlotMarkers->{Automatic,Small},PlotLabel->"Summed Periodograms for 0.0001 blockage",AxesLabel->{"Segment Index","Sum of Periodogram "},ImageSize->Large]*)


(* ::Input:: *)
(*(*Initialize the list to store the sum of periodograms with 0.0001 decay rate for micromobility*)*)
(*sumPeriodograms5={};*)
(**)
(*(*Calculate the number of segments*)*)
(*numSegments5=Quotient[Length[movingAvg4],500];*)
(**)
(*(*Loop through each segment*)*)
(*For[i=1,i<=numSegments5,i++,*)
(*(*Extract the i^th segment of 500 values*)*)
(*blockSegment5=Take[movingAvg4,{500*(i-1)+1,500*i}];*)
(*(*Compute the periodogram for the current segment*)*)
(*periodogram5=PeriodogramArray[blockSegment5];*)
(*(*Sum up the values of the periodogram*)*)
(*sumPeriodogram5=Total[periodogram5];*)
(*(*Append the sum to the list*)*)
(*AppendTo[sumPeriodograms5,sumPeriodogram5];]*)
(**)
(*(*Output the list of summed periodograms for micromobility trace*)*)
(*sumPeriodograms5*)
(*(*Plot the summed periodograms for 0.0001*)*)
(*ListLinePlot[sumPeriodograms5,PlotRange->All,*)
(*PlotLabel->"Summed Periodograms for 0.0001 micromobility",*)
(*AxesLabel->{"Segment Index","Sum of Periodogram "}]*)
(*(*Plot the summed periodograms with smaller dots and thinner lines*)ListPlot[sumPeriodograms5,Joined->True,PlotStyle->{Blue,Thin},PlotRange->All,PlotMarkers->{Automatic,Small},PlotLabel->"Summed Periodograms for 0.0001 micromobility",AxesLabel->{"Segment Index","Sum of Periodogram "},ImageSize->Large]*)


(* ::Input:: *)
(*ListLinePlot[{sumPeriodograms5,sumPeriodograms4-125900},PlotRange->{{0,165},All},PlotStyle->{BlueGray},PlotLabel->"Summed Periodograms for 0.0001 micromobility & blockage",PlotLegends->Placed[{"Micro in 0.0001","Block in 0.0001"},{0.2,0.8}]]*)
